### PR TITLE
Make `consume` and `ContextConsumer` return `undefined` rather than `null`

### LINKED ISSUE #29: Types for `ContextConsumer`
Why is the `default` block of `ContextConsumer` marked as [returning](https://github.com/customerio/ember-provide-consume-context/blob/ember-provide-consume-context%400.3.2/ember-provide-consume-context/src/components/context-consumer.ts#L11) `null`? Why not `undefined` instead? Or why isn't that left to the user of the `ContextRegistry` to decide? `null` doesn't make sense. If the value is not there, `undefined` would be returned, not `null`. I think that should be changed.

### PR DESCRIPTION
**Pull request by boris-petrov**
Fixes #29 

cc @kevinkucharczyk

I'm not sure I've done the change correctly - running `npm lint` locally seems to lead to a lot of TypeScript errors which I'm unsure how to fix. Please take a look and let me know if I've done something wrong.

### CODE REVIEW

**Comment by kevinkucharczyk** [comment]
@boris-petrov what TypeScript errors are you seeing? When I run it locally I see a few warnings:
CleanShot 2024-09-10 at 08 44 42@2x

But they were before - nothing related to your changes. There are no errors and the linting passes correctly.

**Comment by boris-petrov** [comment]
Well, running `npm run lint` leads to these:

```
[lint:types] app/components/a-component.ts(2,25): error TS2307: Cannot find module 'ember-provide-consume-context' or its corresponding type declarations.
[lint:types] app/components/custom-provider.ts(2,25): error TS2307: Cannot find module 'ember-provide-consume-context'or its corresponding type declarations.
[lint:types] app/components/custom-provider.ts(3,34): error TS2307: Cannot find module 'ember-provide-consume-context/context-registry' or its corresponding type declarations.
[lint:types] app/components/custom-provider.ts(28,16): error TS2664: Invalid module name in augmentation, module 'ember-provide-consume-context/context-registry' cannot be found.
[lint:types] app/components/test-component.ts(2,25): error TS2307: Cannot find module 'ember-provide-consume-context' or its corresponding type declarations.
[lint:types] app/components/test-component.ts(3,34): error TS2307: Cannot find module 'ember-provide-consume-context/context-registry' or its corresponding type declarations.
[lint:types] app/controllers/application.ts(33,16): error TS2664: Invalid module name in augmentation, module 'ember-provide-consume-context/context-registry' cannot be found.
[lint:types] tests/integration/components/decorators-test.ts(7,34): error TS2307: Cannot find module 'ember-provide-consume-context' or its corresponding type declarations.
[lint:types] tests/integration/components/test-support-test.ts(8,8): error TS2307: Cannot find module 'ember-provide-consume-context/test-support' or its corresponding type declarations.
[lint:types] types/global.d.ts(3,47): error TS2307: Cannot find module 'ember-provide-consume-context/template-registry' or its corresponding type declarations.
```

And below there's a lot more. One of them:

```
[lint:types] app/templates/application.hbs:75:13 - error TS7053: Unknown name 'ContextProvider'. If this isn't a typo,you may be missing a registry entry for this value; see the Template Registry page in the Glint documentation for moredetails.
[lint:types]   Element implicitly has an 'any' type because expression of type '"ContextProvider"' can't be used to index type 'Globals'.
[lint:types]     Property 'ContextProvider' does not exist on type 'Globals'.
[lint:types]
[lint:types]  75             <ContextProvider @key="NumberContext" @value={{9}}>
[lint:types]                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[lint:types]  76               <BComponent />
[lint:types]     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[lint:types] ...
[lint:types]  79               </ContextConsumer>
[lint:types]     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[lint:types]  80             </ContextProvider>
[lint:types]     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

That doesn't happen when you clone the repo, `npm i` and then `npm run lint`?

**Comment by kevinkucharczyk** [comment]
@boris-petrov I am not seeing those on my machine! What versions of node and npm are you on?

**Comment by boris-petrov** [comment]
Node v22.8.0, npm 10.8.3. I don't think these should matter in that case though.

**Comment by kevinkucharczyk** [comment]
@boris-petrov I can't seem to reproduce what you're seeing. You said you weren't sure if your **changes** are correct - does this mean running `npm lint` against the `main` branch works fine for you?

**Comment by boris-petrov** [comment]
No, the same thing happens on `main`, that's why I can't be sure that my changes are correct. It's really strange that you don't see what I see. As I said, my setup is pretty ordinary - Arch Linux, latest Node/npm, but these things shouldn't really matter. But in any case - CI here is happy so the problem should be somewhere on my machine. Not sure if we can also add/change a test somewhere for this PR?

**Comment by kevinkucharczyk** [comment]
@boris-petrov 
> Not sure if we can also add/change a test somewhere for this PR?

We can definitely add some tests!
There are integration test under `test-app`:
- [a file for the built in components](https://github.com/customerio/ember-provide-consume-context/blob/8150aaff5a757d703dd5e3f2f4dc4d997b59efe9/test-app/tests/integration/components/built-in-components-test.ts)
- [a file for the decorators](https://github.com/customerio/ember-provide-consume-context/blob/8150aaff5a757d703dd5e3f2f4dc4d997b59efe9/test-app/tests/integration/components/decorators-test.ts)

It would make sense to add a test case in each to test what the result is when no provider is present.

Would you like to add those?

**Comment by boris-petrov** [comment]
Sorry for the delay. I’ll try to do that end of next week.

**Comment by boris-petrov** [comment]
@kevinkucharczyk I've added two tests for the two changes. I also found why I was getting these errors. Apparently one must *build* an addon before one can use it. :smile: Didn't know that. So once I ran `npm run build` I could get both linting and tests running fine.

**Review by kevinkucharczyk — APPROVED** [review]

**Pull request merged**
